version: '2'
services:
  server_api_dev:
    build: ./server_api
    container_name: server_api_dev
    network_mode: host
    volumes:
      - ./server_api:/home/app
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/media_server/plex:/config
      - /media/briantv/TV/tv:/data/tvshows
      - /media/briantv/TV/movies:/data/movies
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/media_server/sonarr:/config
      - /media/briantv/TV:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/media_server/radarr:/config
      - /media/briantv/TV:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ~/media_server/jackett:/config
      - /media/briantv/TV/torrent_files:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/media_server/transmission:/config
      - /media/briantv/TV:/data
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/media_server/ombi:/config
      - /media/briantv/TV/tv:/tv
      - /media/briantv/TV/movies:/movies
    ports:
      - 3579:3579
    restart: unless-stopped
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ~/media_server/tautalli:/config
      - ~/media_server/plex/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped